#pragma once

#include <raylib.h>
#include <raymath.h>

#include "components/sprite.h"

// Audio : background music for now
typedef enum {
  BGM_FAST_DANGER,
  BGM_QUIRKY_GOOFY,
  BGM_TO_BE_NAMED, // maybe won't be used
  BGM_WAITING,
  BGM_MORIYA_THEME,
  MAX_BGM // Pour savoir combien on en a
} BGMId;

typedef enum {
  BULLET_SPRITESHEET,
  ENEMY_SPRITESHEET,
  BOSS_SPRITESHEET,
  ANIM_TEST_SPRITESHEET,
  REIMU_SPRITESHEET,
  HITBOX_SPRITESHEET,
  MAX_TEXTURES
} TextureID;

typedef enum {
  NULL_SPRITE,

  // Player
  
  ANIM_TEST,

  REIMU_IDLE,
  REIMU_RIGHT,
  REIMU_LEFT,
  REIMU_PINK_AMULET,

  HITBOX,

  //BULLETS -----------------------------------
  BALL_M_BLACK,

  // ------ LASERS
  LASER_BLACK,
  LASER_RED,
  LASER_LIGHT_RED,
  LASER_PINK,
  LASER_LIGHT_PINK,
  LASER_BLUE,
  LASER_LIGHT_BLUE,
  LASER_CYAN,
  LASER_LIGHT_CYAN,
  LASER_GREEN,
  LASER_LIGHT_GREEN,
  LASER_LIME,
  LASER_YELLOW,
  LASER_LIGHT_YELLOW,
  LASER_GOLD,
  LASER_WHITE,

  // ------ MISSILES
  MISSILE_BLACK,
  MISSILE_RED,
  MISSILE_LIGHT_RED,
  MISSILE_PINK,
  MISSILE_LIGHT_PINK,
  MISSILE_BLUE,
  MISSILE_LIGHT_BLUE,
  MISSILE_CYAN,
  MISSILE_LIGHT_CYAN,
  MISSILE_GREEN,
  MISSILE_LIGHT_GREEN,
  MISSILE_LIME,
  MISSILE_YELLOW,
  MISSILE_LIGHT_YELLOW,
  MISSILE_GOLD,
  MISSILE_WHITE,


  // ------ RING BULLETS
  BULLET_RING_BLACK,
  BULLET_RING_RED,
  BULLET_RING_LIGHT_RED,
  BULLET_RING_PINK,
  BULLET_RING_LIGHT_PINK,
  BULLET_RING_BLUE,
  BULLET_RING_LIGHT_BLUE,
  BULLET_RING_CYAN,
  BULLET_RING_LIGHT_CYAN,
  BULLET_RING_GREEN,
  BULLET_RING_LIGHT_GREEN,
  BULLET_RING_LIME,
  BULLET_RING_YELLOW,
  BULLET_RING_LIGHT_YELLOW,
  BULLET_RING_GOLD,
  BULLET_RING_WHITE,
  
  // ------ BULLETS
  BULLET_BLACK,
  BULLET_RED,
  BULLET_LIGHT_RED,
  BULLET_PINK,
  BULLET_LIGHT_PINK,
  BULLET_BLUE,
  BULLET_LIGHT_BLUE,
  BULLET_CYAN,
  BULLET_LIGHT_CYAN,
  BULLET_GREEN,
  BULLET_LIGHT_GREEN,
  BULLET_LIME,
  BULLET_YELLOW,
  BULLET_LIGHT_YELLOW,
  BULLET_GOLD,
  BULLET_WHITE,

  // ------ PETALS
  PETAL_BLACK,
  PETAL_RED,
  PETAL_LIGHT_RED,
  PETAL_PINK,
  PETAL_LIGHT_PINK,
  PETAL_BLUE,
  PETAL_LIGHT_BLUE,
  PETAL_CYAN,
  PETAL_LIGHT_CYAN,
  PETAL_GREEN,
  PETAL_LIGHT_GREEN,
  PETAL_LIME,
  PETAL_YELLOW,
  PETAL_LIGHT_YELLOW,
  PETAL_GOLD,
  PETAL_WHITE,

  // ------ KUNAI
  KUNAI_BLACK,
  KUNAI_RED,
  KUNAI_LIGHT_RED,
  KUNAI_PINK,
  KUNAI_LIGHT_PINK,
  KUNAI_BLUE,
  KUNAI_LIGHT_BLUE,
  KUNAI_CYAN,
  KUNAI_LIGHT_CYAN,
  KUNAI_GREEN,
  KUNAI_LIGHT_GREEN,
  KUNAI_LIME,
  KUNAI_YELLOW,
  KUNAI_LIGHT_YELLOW,
  KUNAI_GOLD,
  KUNAI_WHITE,

  // ------ SHARDS
  SHARD_BLACK,
  SHARD_RED,
  SHARD_LIGHT_RED,
  SHARD_PINK,
  SHARD_LIGHT_PINK,
  SHARD_BLUE,
  SHARD_LIGHT_BLUE,
  SHARD_CYAN,
  SHARD_LIGHT_CYAN,
  SHARD_GREEN,
  SHARD_LIGHT_GREEN,
  SHARD_LIME,
  SHARD_YELLOW,
  SHARD_LIGHT_YELLOW,
  SHARD_GOLD,
  SHARD_WHITE,

  // ------ TALISMANS
  TALISMAN_BLACK,
  TALISMAN_RED,
  TALISMAN_LIGHT_RED,
  TALISMAN_PINK,
  TALISMAN_LIGHT_PINK,
  TALISMAN_BLUE,
  TALISMAN_LIGHT_BLUE,
  TALISMAN_CYAN,
  TALISMAN_LIGHT_CYAN,
  TALISMAN_GREEN,
  TALISMAN_LIGHT_GREEN,
  TALISMAN_LIME,
  TALISMAN_YELLOW,
  TALISMAN_LIGHT_YELLOW,
  TALISMAN_GOLD,
  TALISMAN_WHITE,

  // ------ DARK PETALS
  DARK_PETAL_BLACK,
  DARK_PETAL_RED,
  DARK_PETAL_LIGHT_RED,
  DARK_PETAL_PINK,
  DARK_PETAL_LIGHT_PINK,
  DARK_PETAL_BLUE,
  DARK_PETAL_LIGHT_BLUE,
  DARK_PETAL_CYAN,
  DARK_PETAL_LIGHT_CYAN,
  DARK_PETAL_GREEN,
  DARK_PETAL_LIGHT_GREEN,
  DARK_PETAL_LIME,
  DARK_PETAL_YELLOW,
  DARK_PETAL_LIGHT_YELLOW,
  DARK_PETAL_GOLD,
  DARK_PETAL_WHITE,

  // ------ DARK PETALS
  GUNSHOT_BLACK,
  GUNSHOT_RED,
  GUNSHOT_LIGHT_RED,
  GUNSHOT_PINK,
  GUNSHOT_LIGHT_PINK,
  GUNSHOT_BLUE,
  GUNSHOT_LIGHT_BLUE,
  GUNSHOT_CYAN,
  GUNSHOT_LIGHT_CYAN,
  GUNSHOT_GREEN,
  GUNSHOT_LIGHT_GREEN,
  GUNSHOT_LIME,
  GUNSHOT_YELLOW,
  GUNSHOT_LIGHT_YELLOW,
  GUNSHOT_GOLD,
  GUNSHOT_WHITE,

  // ------ STARS
  STAR_BLACK,
  STAR_RED,
  STAR_LIGHT_RED,
  STAR_PINK,
  STAR_LIGHT_PINK,
  STAR_BLUE,
  STAR_LIGHT_BLUE,
  STAR_CYAN,
  STAR_LIGHT_CYAN,
  STAR_GREEN,
  STAR_LIGHT_GREEN,
  STAR_LIME,
  STAR_YELLOW,
  STAR_LIGHT_YELLOW,
  STAR_GOLD,
  STAR_WHITE,

  // ------ BALL
  BALL_BLACK,
  BALL_RED,
  BALL_LIGHT_RED,
  BALL_PINK,
  BALL_LIGHT_PINK,
  BALL_BLUE,
  BALL_LIGHT_BLUE,
  BALL_CYAN,
  BALL_LIGHT_CYAN,
  BALL_GREEN,
  BALL_LIGHT_GREEN,
  BALL_LIME,
  BALL_YELLOW,
  BALL_LIGHT_YELLOW,
  BALL_GOLD,
  BALL_WHITE,

  // ------ MINI BULLETS
  DARK_BULLET_MINI_BLACK,
  DARK_BULLET_MINI_RED,
  DARK_BULLET_MINI_LIGHT_RED,
  DARK_BULLET_MINI_PINK,
  DARK_BULLET_MINI_LIGHT_PINK,
  DARK_BULLET_MINI_BLUE,
  DARK_BULLET_MINI_LIGHT_BLUE,
  DARK_BULLET_MINI_CYAN,
  DARK_BULLET_MINI_LIGHT_CYAN,
  DARK_BULLET_MINI_GREEN,
  DARK_BULLET_MINI_LIGHT_GREEN,
  DARK_BULLET_MINI_LIME,
  DARK_BULLET_MINI_YELLOW,
  DARK_BULLET_MINI_LIGHT_YELLOW,
  DARK_BULLET_MINI_GOLD,
  DARK_BULLET_MINI_WHITE,

  BULLET_MINI_BLACK,
  BULLET_MINI_RED,
  BULLET_MINI_LIGHT_RED,
  BULLET_MINI_PINK,
  BULLET_MINI_LIGHT_PINK,
  BULLET_MINI_BLUE,
  BULLET_MINI_LIGHT_BLUE,
  BULLET_MINI_CYAN,
  BULLET_MINI_LIGHT_CYAN,
  BULLET_MINI_GREEN,
  BULLET_MINI_LIGHT_GREEN,
  BULLET_MINI_LIME,
  BULLET_MINI_YELLOW,
  BULLET_MINI_LIGHT_YELLOW,
  BULLET_MINI_GOLD,
  BULLET_MINI_WHITE,

  // ------ BULLET M
  BULLET_M_BLACK,
  BULLET_M_RED,
  BULLET_M_BLUE,
  BULLET_M_GREEN,
  BULLET_M_YELLOW,
  RING_M_BLACK,
  RING_M_RED,
  RING_M_BLUE,
  RING_M_GREEN,
  RING_M_YELLOW,

  // ------ BIG HEARTS
  BIG_HEART_BLACK,
  BIG_HEART_RED,
  BIG_HEART_PINK,
  BIG_HEART_BLUE,
  BIG_HEART_CYAN,
  BIG_HEART_GREEN,
  BIG_HEART_YELLOW,
  BIG_HEART_WHITE,

  // ------------ ENEMIES

  // ------ SMALL FAIRIES

  ENEMY_FAIRY_BLUE_IDLE,
  ENEMY_FAIRY_BLUE_MOVE,

  ENEMY_FAIRY_RED_IDLE,
  ENEMY_FAIRY_RED_MOVE,

  ENEMY_FAIRY_BLACK_BLONDE_IDLE,
  ENEMY_FAIRY_BLACK_BLONDE_MOVE,

  ENEMY_FAIRY_GREEN_IDLE,
  ENEMY_FAIRY_GREEN_MOVE,

  ENEMY_FAIRY_PURPLE_IDLE,
  ENEMY_FAIRY_PURPLE_MOVE,

  // ------ BIG FAIRIES

  ENEMY_FAIRY_BIG_SUNFLOWER_IDLE,
  ENEMY_FAIRY_BIG_SUNFLOWER_MOVE,

  ENEMY_FAIRY_BIG_EVIL_IDLE,
  ENEMY_FAIRY_BIG_EVIL_MOVE,

  MAX_SPRITES
} SpriteID;




extern void AssetsLoad();
extern void AssetsUnload();
void BulletsSpritesLoad();
extern void SpritesLoad();
void EnemiesSpritesLoad();

extern Texture2D textures[MAX_TEXTURES];
extern Sprite sprites[MAX_SPRITES];
extern Music playlist[MAX_BGM];     

// Effets sonores
typedef enum {
    SFX_SHOOT,
    SFX_ENEMY_DEATH,
    SFX_MENU_NAV,
    SFX_TAN00,
    SFX_TAN01,
    SFX_TAN02,
    SFX_PLDEAD00,
    SFX_GRAZE,
    
    MAX_SFX
} SFXID;

extern Sound sfx[MAX_SFX];

