#ifndef ASSETS_H
#define ASSETS_H

#include <raylib.h>
#include <raymath.h>

#include "components/sprite.h"

// Audio : background music for now
typedef enum {
  BGM_FAST_DANGER,
  BGM_QUIRKY_GOOFY,
  BGM_TO_BE_NAMED, // maybe won't be used
  BGM_WAITING,
  MAX_BGM // Pour savoir combien on en a
} BGMId;

typedef enum {
  BULLET_SPRITESHEET,
  ENEMY_SPRITESHEET,
  BOSS_SPRITESHEET,
  ANIM_TEST_SPRITESHEET,
  REIMU_SPRITESHEET,
  HITBOX_SPRITESHEET,
  MAX_TEXTURES
} TextureID;

typedef enum {
  NULL_SPRITE,

  // Player
  
  ANIM_TEST,

  REIMU_IDLE,
  REIMU_RIGHT,
  REIMU_LEFT,
  REIMU_PINK_AMULET,

  HITBOX,

  //BULLETS 
  BALL_M_BLACK,

  BULLET_SMALL_RED,
  BULLET_SMALL_BLUE,
  BULLET_SMALL_GREEN,
  BULLET_SMALL_YELLOW,

  BULLET_RING_RED,
  BULLET_RING_BLUE,
  BULLET_RING_GREEN,

  BULLET_STAR_RED,
  BULLET_STAR_BLUE,

  BULLET_BIG_RED,
  BULLET_BIG_BLUE,

  BULLET_FIRE_RED,
  BULLET_FIRE_BLUE,
  BULLET_FIRE_GREEN,

  BULLET_BLACK_GRADIENT,
  BULLET_PURPLE_GRADIENT,
  BULLET_GREEN_GRADIENT,
  BULLET_YELLOW_GRADIENT,


    //ENEMIES

  // FAIRIES

  ENEMY_FAIRY_BLUE_IDLE,
  ENEMY_FAIRY_BLUE_MOVE,

  ENEMY_FAIRY_RED_IDLE,
  ENEMY_FAIRY_RED_MOVE,

  ENEMY_FAIRY_CYAN_IDLE,
  ENEMY_FAIRY_CYAN_MOVE,

  // FAIRY VARIANTS

  ENEMY_FAIRY_GREEN_IDLE,
  ENEMY_FAIRY_GREEN_MOVE,

  ENEMY_FAIRY_YELLOW_IDLE,
  ENEMY_FAIRY_YELLOW_MOVE,

  // BUTTERFLIES

  ENEMY_BUTTERFLY_BLUE_IDLE,
  ENEMY_BUTTERFLY_BLUE_MOVE,

  ENEMY_BUTTERFLY_RED_IDLE,
  ENEMY_BUTTERFLY_RED_MOVE,

  // BIG FAIRIES

  ENEMY_BIG_FAIRY_IDLE,
  ENEMY_BIG_FAIRY_MOVE,

  MAX_SPRITES
} SpriteID;




extern void AssetsLoad();
extern void AssetsUnload();
void BulletsSpritesLoad();
extern void SpritesLoad();
void EnemiesSpritesLoad();

extern Texture2D textures[MAX_TEXTURES];
extern Sprite sprites[MAX_SPRITES];
extern Music playlist[MAX_BGM];      

// Effets sonores
typedef enum {
    SFX_SHOOT,
    SFX_ENEMY_DEATH,
    SFX_MENU_NAV,
    MAX_SFX
} SFXID;

extern Sound sfx[MAX_SFX];

#endif
