//FICHIER QUI DEFINIE LA TAILLE DES DIFFERENTES PARTIES DE L'ECRAN
#pragma once

#define DRAW_MARGIN 500   // 80
#define SCREEN_WIDTH 1280 // 1280
#define SCREEN_HEIGHT 900 // 900

#define PANEL_LEFT SCREEN_WIDTH / 64      // 10
#define PANEL_WIDTH SCREEN_WIDTH / 2      // 700
#define PANEL_UP SCREEN_HEIGHT / 45       // 20
#define PANEL_HEIGHT SCREEN_HEIGHT * 0.95 // 820

